---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }} # Must match `--ds-name`
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: kured
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /usr/bin/kured
          args:
            - --ds-name={{ .Release.Name }}
            - --ds-namespace={{ .Release.Namespace }}
            - --lock-annotation=weave.works/kured-node-lock
            - --period=24h
            - --reboot-sentinel=/var/run/reboot-required
            - --slack-hook-url={{ .Values.slackWebhookUrl }}
            - --slack-username={{ .Values.slackUsername }}
          env:
            - name: KURED_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: hostrun
              mountPath: /var/run
      restartPolicy: Always
      volumes:
        - name: hostrun
          hostPath:
            path: /var/run
